### ISSUE TITLE
The game crashes after a few seconds

### ISSUE THREAD

**Issue by Nav33nn** [UpGado/ascii_racer#5]
Here is the stack trace

Traceback (most recent call last):
  File "/home/naveen/anaconda3/bin/asciiracer", line 11, in <module>
    load_entry_point('asciiracer==0.1.1', 'console_scripts', 'asciiracer')()
  File "/home/naveen/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/naveen/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/home/naveen/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/naveen/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/naveen/anaconda3/lib/python3.6/site-packages/asciiracer/__main__.py", line 1, in <module>
    from . import game
  File "/home/naveen/anaconda3/lib/python3.6/site-packages/asciiracer/game.py", line 54, in <module>
    curses.wrapper(main)
  File "/home/naveen/anaconda3/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/naveen/anaconda3/lib/python3.6/site-packages/asciiracer/game.py", line 40, in main
    draw_scene(screen)
  File "/home/naveen/anaconda3/lib/python3.6/site-packages/asciiracer/misc.py", line 17, in run
    raise RuntimeError('cannot keep up with target FPS')
RuntimeError: cannot keep up with target FPS

**Comment by UpGado** [comment]
I suspect that your computer can't handle the game at the target FPS, which defaults to 60. Currently, there is no way to change the FPS unless you change the source code. Try and edit the config.py file, which would reside on your system at `/home/naveen/anaconda3/lib/python3.6/site-packages/asciiracer/config.py` and lower the FPS to something like 30. Let me know if that works.

**Comment by Nav33nn** [comment]
Works perfectly fine! Thanks!
